#!/usr/bin/env python3
"""
Read .acss-kit/manifest.json from a project root and emit it as JSON.

The manifest is the kit-sync state file: it records every file generated by
/kit-sync along with the sha256 of the (normalized) content at the time it
was written, so /kit-update can detect user modifications via drift checks.

Usage:
    python3 manifest_read.py [project_root]

Output (JSON to stdout):

    Manifest exists:
    {
      "exists": true,
      "path": "/abs/.acss-kit/manifest.json",
      "schemaVersion": 1,
      "pluginVersion": "0.9.0",
      "targetDir": "src/components/fpkit",
      "stylesDir": "src/styles",
      "themeFile": "acss-kit.theme.json",
      "generatedAt": "2026-05-03T14:22:11Z",
      "files": { "<rel-path>": { "source": "...", "sha256": "...", ... } },
      "reasons": []
    }

    Manifest missing:
    {
      "exists": false,
      "path": "/abs/.acss-kit/manifest.json",
      "files": {},
      "reasons": ["Manifest not found. Run /kit-sync first."]
    }

Exit codes:
    0 — manifest exists and parsed
    1 — manifest missing or invalid
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


MANIFEST_REL = ".acss-kit/manifest.json"
SCHEMA_VERSION = 1


def main() -> int:
    start = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
    manifest_path = start / MANIFEST_REL

    if not manifest_path.is_file():
        print(json.dumps({
            "exists": False,
            "path": str(manifest_path),
            "files": {},
            "reasons": ["Manifest not found. Run /kit-sync first."],
        }, indent=2))
        return 1

    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as e:
        print(json.dumps({
            "exists": False,
            "path": str(manifest_path),
            "files": {},
            "reasons": [f"Manifest unreadable: {e}"],
        }, indent=2))
        return 1

    if not isinstance(data, dict) or "files" not in data:
        print(json.dumps({
            "exists": False,
            "path": str(manifest_path),
            "files": {},
            "reasons": ["Manifest malformed: missing 'files' object."],
        }, indent=2))
        return 1

    if not isinstance(data["files"], dict):
        print(json.dumps({
            "exists": False,
            "path": str(manifest_path),
            "files": {},
            "reasons": [
                f"Manifest malformed: 'files' must be an object, got {type(data['files']).__name__}."
            ],
        }, indent=2))
        return 1

    schema_version = data.get("schemaVersion", 0)
    schema_mismatch = schema_version != SCHEMA_VERSION
    reasons = (
        [f"Manifest schemaVersion {schema_version} != expected {SCHEMA_VERSION}."]
        if schema_mismatch
        else []
    )

    out = {
        "exists": not schema_mismatch,
        "path": str(manifest_path),
        "schemaVersion": schema_version,
        "pluginVersion": data.get("pluginVersion", ""),
        "targetDir": data.get("targetDir", ""),
        "stylesDir": data.get("stylesDir", ""),
        "themeFile": data.get("themeFile", ""),
        "generatedAt": data.get("generatedAt", ""),
        "files": data.get("files", {}),
        "reasons": reasons,
    }
    print(json.dumps(out, indent=2))
    return 1 if schema_mismatch else 0


if __name__ == "__main__":
    sys.exit(main())
