#!/usr/bin/env python3
"""
Convert a theme.tokens.json file into CSS theme files.

Usage:
    python tokens_to_css.py <tokens.json> [--out-dir=<dir>]
    python tokens_to_css.py --stdin [--out-dir=<dir>]   (reads JSON from stdin)

Output: writes light.css and/or dark.css (and brand-<name>.css for each brand)
        to --out-dir (default: current directory). Prints file paths written.

Exit codes: 0 = success, 1 = validation error, 2 = usage/IO error.

CSS variable convention (CLAUDE.md §CSS variable naming):
  - Every var() reference includes a hardcoded hex fallback.
  - :root { } for light mode tokens.
  - [data-theme="dark"] { } for dark mode tokens.
  - Brand files use both selectors with only overridden roles.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path


LIGHT_HEADER = """\
/* light.css — semantic role tokens for the light theme.
 * Generated by acss-kit /theme-create.
 * WCAG AA verified by validate_theme.py.
 */
"""

DARK_HEADER = """\
/* dark.css — semantic role tokens for the dark theme.
 * Generated by acss-kit /theme-create.
 * Scoped under [data-theme="dark"] — set this attribute on <html>.
 */
"""

BRAND_HEADER = """\
/* brand-{name}.css — brand color overrides.
 * Generated by acss-kit /theme-brand.
 * Layer this import AFTER light.css and dark.css.
 */
"""

ROLE_GROUPS = [
    ("Backgrounds", ["--color-background", "--color-surface", "--color-surface-raised", "--color-surface-subtle"]),
    ("Text", ["--color-text", "--color-text-muted", "--color-text-inverse", "--color-text-subtle"]),
    ("Borders", ["--color-border", "--color-border-strong"]),
    ("Brand + semantic", ["--color-primary", "--color-primary-hover", "--color-success", "--color-warning", "--color-danger", "--color-info"]),
    ("Focus", ["--color-focus-ring"]),
    ("Accent", ["--color-brand-accent"]),
]


def _format_palette(palette: dict[str, str], selector: str, indent: str = "  ") -> str:
    lines = [f"{selector} {{"]
    for group_name, roles in ROLE_GROUPS:
        group_lines = []
        for role in roles:
            if role in palette:
                val = palette[role]
                # Every var() reference includes a hardcoded hex fallback per CLAUDE.md
                group_lines.append(f"{indent}{role}: var({role}, {val});")
        if group_lines:
            lines.append(f"\n{indent}/* {group_name} */")
            lines.extend(group_lines)
    lines.append("}\n")
    return "\n".join(lines)


def _write_light(palette: dict[str, str], out_dir: Path) -> Path:
    content = LIGHT_HEADER + "\n" + _format_palette(palette, ":root")
    # Strip double-blank lines
    path = out_dir / "light.css"
    path.write_text(content, encoding="utf-8")
    return path


def _write_dark(palette: dict[str, str], out_dir: Path) -> Path:
    content = DARK_HEADER + "\n" + _format_palette(palette, '[data-theme="dark"]')
    path = out_dir / "dark.css"
    path.write_text(content, encoding="utf-8")
    return path


def _write_brand(name: str, overrides: dict, out_dir: Path) -> Path:
    header = BRAND_HEADER.replace("{name}", name)
    light_overrides = overrides.get("light", overrides)
    dark_overrides = overrides.get("dark", {})
    content = header + "\n"
    if light_overrides:
        content += _format_palette(light_overrides, ":root") + "\n"
    if dark_overrides:
        content += _format_palette(dark_overrides, '[data-theme="dark"]') + "\n"
    path = out_dir / f"brand-{name}.css"
    path.write_text(content, encoding="utf-8")
    return path


def main() -> int:
    args = sys.argv[1:]
    out_dir = Path(".")
    use_stdin = False
    input_path: Path | None = None

    for a in args:
        if a == "--stdin":
            use_stdin = True
        elif a.startswith("--out-dir="):
            out_dir = Path(a.split("=", 1)[1])
        elif not a.startswith("--"):
            input_path = Path(a)

    if not use_stdin and input_path is None:
        print("usage: tokens_to_css.py <tokens.json> [--out-dir=<dir>]", file=sys.stderr)
        return 2

    try:
        if use_stdin:
            tokens = json.load(sys.stdin)
        else:
            tokens = json.loads(input_path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"error reading tokens: {e}", file=sys.stderr)
        return 2

    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[str] = []

    modes = tokens.get("modes", {})
    if "light" in modes:
        p = _write_light(modes["light"], out_dir)
        written.append(str(p))
    if "dark" in modes:
        p = _write_dark(modes["dark"], out_dir)
        written.append(str(p))

    for brand_name, overrides in tokens.get("brands", {}).items():
        p = _write_brand(brand_name, overrides, out_dir)
        written.append(str(p))

    if not written:
        print("tokens_to_css: nothing to write (no modes or brands in tokens)", file=sys.stderr)
        return 1

    for f in written:
        print(f"wrote: {f}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
