// Generated by acss-app-builder /app-layout holy-grail
// {{IMPORT_SOURCE:}}
import type { ReactNode } from 'react'
import './AppShell.scss'

export type AppShellProps = {
  header?: ReactNode
  nav?: ReactNode
  aside?: ReactNode
  footer?: ReactNode
  children: ReactNode
}

export default function AppShell({ header, nav, aside, footer, children }: AppShellProps) {
  return (
    <div className="app-shell" data-shell="holy-grail">
      {header && <header className="app-shell__header">{header}</header>}
      {nav && <nav className="app-shell__nav" aria-label="Primary">{nav}</nav>}
      <main className="app-shell__main" id="main">
        {children}
      </main>
      {aside && <aside className="app-shell__aside" aria-label="Complementary">{aside}</aside>}
      {footer && <footer className="app-shell__footer">{footer}</footer>}
    </div>
  )
}
