// Generated by acss-app-builder /app-layout centered
// {{IMPORT_SOURCE:}}
import type { ReactNode } from 'react'
import './AppShell.scss'

export type AppShellProps = {
  children: ReactNode
}

export default function AppShell({ children }: AppShellProps) {
  return (
    <div className="app-shell" data-shell="centered">
      <main className="app-shell__main" id="main">
        {children}
      </main>
    </div>
  )
}
