// Generated by acss-app-builder /app-page auth-signup
// {{IMPORT_SOURCE:Field,Input,Checkbox,Button,Link}}
import { useState, type FormEvent } from 'react'

export default function {{NAME}}() {
  const [submitting, setSubmitting] = useState(false)

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setSubmitting(true)
    try {
      const data = new FormData(e.currentTarget)
      console.log('signup', Object.fromEntries(data))
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <section aria-labelledby="signup-heading" className="auth">
      <h1 id="signup-heading">Create your account</h1>
      <form onSubmit={handleSubmit} noValidate>
        <Field label="Full name" labelFor="signup-name">
          <Input id="signup-name" type="text" name="name" required autoComplete="name" />
        </Field>
        <Field label="Email" labelFor="signup-email">
          <Input id="signup-email" type="email" name="email" required autoComplete="email" />
        </Field>
        <Field label="Password" labelFor="signup-password">
          <Input
            id="signup-password"
            type="password"
            name="password"
            required
            autoComplete="new-password"
            minLength={8}
            aria-describedby="signup-password-help"
          />
          <span id="signup-password-help">Minimum 8 characters.</span>
        </Field>
        <Field label="I agree to the Terms of Service" labelFor="signup-terms">
          <Checkbox id="signup-terms" name="terms" required />
        </Field>
        <Button type="submit" aria-disabled={submitting} data-color="primary">
          {submitting ? 'Creating…' : 'Create account'}
        </Button>
      </form>
      <p>
        Already have an account? <Link href="/login">Sign in</Link>
      </p>
    </section>
  )
}
