// Generated by acss-app-builder /app-page landing
// {{IMPORT_SOURCE:Button,Link,Card,CardTitle,CardContent}}

export default function {{NAME}}() {
  return (
    <>
      {/* Hero */}
      <section aria-labelledby="hero-heading" className="hero">
        <h1 id="hero-heading">Build fast. Ship accessible.</h1>
        <p>A starter app powered by the @fpkit/acss design system.</p>
        <Button type="button" data-color="primary">Get started</Button>{' '}
        <Link href="/docs">Read the docs</Link>
      </section>

      {/* Features */}
      <section aria-labelledby="features-heading" className="features">
        <h2 id="features-heading">What you get</h2>
        <div className="features__grid" role="list">
          <Card role="listitem">
            <CardTitle>Accessible by default</CardTitle>
            <CardContent>WCAG AA components with keyboard + screen-reader support.</CardContent>
          </Card>
          <Card role="listitem">
            <CardTitle>CSS custom properties</CardTitle>
            <CardContent>Theme any component with standard tokens — no framework lock-in.</CardContent>
          </Card>
          <Card role="listitem">
            <CardTitle>Ship-ready layouts</CardTitle>
            <CardContent>Shells, pages, and patterns scaffolded from one command.</CardContent>
          </Card>
        </div>
      </section>

      {/* Pricing — insert the pricing-grid pattern here with:
          /app-pattern pricing-grid --into=src/pages/{{NAME}}.tsx */}
      {/* @acss-app-builder:insert */}
    </>
  )
}
