// Generated by acss-app-builder /app-page list-detail
// {{IMPORT_SOURCE:TBL,Button,Dialog}}
import { useState } from 'react'

type Item = { id: string; name: string; status: 'active' | 'archived' }

const SEED: Item[] = [
  { id: '1', name: 'Project Alpha', status: 'active' },
  { id: '2', name: 'Project Beta',  status: 'active' },
  { id: '3', name: 'Project Gamma', status: 'archived' },
]

export default function {{NAME}}() {
  const [items] = useState<Item[]>(SEED)
  const [selected, setSelected] = useState<Item | null>(null)

  return (
    <section aria-labelledby="list-heading">
      <h1 id="list-heading">Projects</h1>

      <TBL
        caption="Projects"
        data={items}
        columns={[
          { header: 'Name',   accessor: 'name' },
          { header: 'Status', accessor: 'status' },
          {
            header: 'Actions',
            accessor: 'id',
            cell: (row: Item) => (
              <Button type="button" onClick={() => setSelected(row)}>
                View
              </Button>
            ),
          },
        ]}
      />

      {selected && (
        <Dialog
          open
          onClose={() => setSelected(null)}
          aria-labelledby="detail-heading"
        >
          <h2 id="detail-heading">{selected.name}</h2>
          <p>Status: {selected.status}</p>
          <Button type="button" onClick={() => setSelected(null)}>Close</Button>
        </Dialog>
      )}
    </section>
  )
}
