// Generated by acss-app-builder /app-page settings
// {{IMPORT_SOURCE:Card,Field,Input,Button}}
// Tabs use the WAI-ARIA tablist pattern (NOT the fpkit Details disclosure widget).
import { useState, useRef, type KeyboardEvent } from 'react'

const TABS = [
  { id: 'profile',       label: 'Profile' },
  { id: 'notifications', label: 'Notifications' },
  { id: 'security',      label: 'Security' },
] as const
type TabId = typeof TABS[number]['id']

export default function {{NAME}}() {
  const [active, setActive] = useState<TabId>('profile')
  const tabRefs = useRef<Record<TabId, HTMLButtonElement | null>>({
    profile: null, notifications: null, security: null,
  })

  function focusTab(id: TabId) {
    setActive(id)
    tabRefs.current[id]?.focus()
  }

  function onKeyDown(e: KeyboardEvent<HTMLButtonElement>) {
    const idx = TABS.findIndex((t) => t.id === active)
    if (e.key === 'ArrowRight') { e.preventDefault(); focusTab(TABS[(idx + 1) % TABS.length].id) }
    if (e.key === 'ArrowLeft')  { e.preventDefault(); focusTab(TABS[(idx - 1 + TABS.length) % TABS.length].id) }
    if (e.key === 'Home')       { e.preventDefault(); focusTab(TABS[0].id) }
    if (e.key === 'End')        { e.preventDefault(); focusTab(TABS[TABS.length - 1].id) }
  }

  return (
    <section aria-labelledby="settings-heading">
      <h1 id="settings-heading">Settings</h1>

      <div role="tablist" aria-label="Settings sections" className="settings-tabs">
        {TABS.map((t) => (
          <button
            key={t.id}
            ref={(el) => { tabRefs.current[t.id] = el }}
            role="tab"
            id={`tab-${t.id}`}
            aria-controls={`panel-${t.id}`}
            aria-selected={active === t.id}
            tabIndex={active === t.id ? 0 : -1}
            onClick={() => setActive(t.id)}
            onKeyDown={onKeyDown}
          >
            {t.label}
          </button>
        ))}
      </div>

      <div role="tabpanel" id="panel-profile" aria-labelledby="tab-profile" hidden={active !== 'profile'}>
        <Card>
          <Field label="Display name" labelFor="setting-display-name">
            <Input id="setting-display-name" type="text" name="displayName" />
          </Field>
          <Field label="Email" labelFor="setting-email">
            <Input id="setting-email" type="email" name="email" />
          </Field>
          <Button type="submit" data-color="primary">Save</Button>
        </Card>
      </div>

      <div role="tabpanel" id="panel-notifications" aria-labelledby="tab-notifications" hidden={active !== 'notifications'}>
        <Card>Notification preferences go here.</Card>
      </div>

      <div role="tabpanel" id="panel-security" aria-labelledby="tab-security" hidden={active !== 'security'}>
        <Card>Password and 2FA settings go here.</Card>
      </div>
    </section>
  )
}
