// Generated by acss-app-builder /app-pattern loading-skeleton
// {{IMPORT_SOURCE:}}
import './loading-skeleton.scss'

export type LoadingSkeletonProps = {
  lines?: number
  label?: string
}

export default function LoadingSkeleton({ lines = 3, label = 'Loading' }: LoadingSkeletonProps) {
  return (
    <div className="loading-skeleton" aria-busy="true" aria-label={label}>
      {Array.from({ length: lines }).map((_, i) => (
        <span key={i} className="loading-skeleton__bar" />
      ))}
    </div>
  )
}
