// Generated by acss-app-builder /app-pattern pricing-grid
// {{IMPORT_SOURCE:Card,CardTitle,CardContent,Button}}
import './pricing-grid.scss'

export type PricingTier = {
  name: string
  price: string
  cadence: string
  features: string[]
  ctaLabel: string
  onSelect?: () => void
  recommended?: boolean
}

export type PricingGridProps = {
  tiers: PricingTier[]
}

export default function PricingGrid({ tiers }: PricingGridProps) {
  return (
    <section className="pricing-grid" aria-labelledby="pricing-heading">
      <h2 id="pricing-heading">Pricing</h2>
      <div className="pricing-grid__grid" role="list">
        {tiers.map((t) => (
          <Card
            key={t.name}
            role="listitem"
            data-recommended={t.recommended ? 'true' : undefined}
            aria-current={t.recommended ? 'true' : undefined}
          >
            <CardTitle>{t.name}</CardTitle>
            <CardContent>
              <p className="pricing-grid__price">
                <strong>{t.price}</strong>
                <span>{' '}/{t.cadence}</span>
              </p>
              <ul>
                {t.features.map((f) => <li key={f}>{f}</li>)}
              </ul>
              <Button
                type="button"
                onClick={t.onSelect}
                data-color={t.recommended ? 'primary' : undefined}
              >
                {t.ctaLabel}
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </section>
  )
}
