// Generated by acss-app-builder /app-page auth-login
// {{IMPORT_SOURCE:Field,Input,Button,Link}}
import { useState, type FormEvent } from 'react'

export default function {{NAME}}() {
  const [submitting, setSubmitting] = useState(false)

  async function handleSubmit(e: FormEvent<HTMLFormElement>) {
    e.preventDefault()
    setSubmitting(true)
    try {
      const data = new FormData(e.currentTarget)
      // TODO: wire to your auth endpoint
      console.log('login', Object.fromEntries(data))
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <section aria-labelledby="login-heading" className="auth">
      <h1 id="login-heading">Sign in</h1>
      <form onSubmit={handleSubmit} noValidate>
        <Field label="Email" labelFor="login-email">
          <Input
            id="login-email"
            type="email"
            name="email"
            required
            autoComplete="email"
          />
        </Field>
        <Field label="Password" labelFor="login-password">
          <Input
            id="login-password"
            type="password"
            name="password"
            required
            autoComplete="current-password"
            minLength={8}
          />
        </Field>
        <Button type="submit" aria-disabled={submitting} data-color="primary">
          {submitting ? 'Signing in…' : 'Sign in'}
        </Button>
      </form>
      <p>
        <Link href="/forgot-password">Forgot your password?</Link>
      </p>
    </section>
  )
}
