// Generated by acss-app-builder /app-page dashboard
// {{IMPORT_SOURCE:Card,CardTitle,CardContent,TBL}}

export default function {{NAME}}() {
  const stats = [
    { label: 'Revenue', value: '$12,430' },
    { label: 'Active users', value: '1,284' },
    { label: 'Conversion', value: '3.4%' },
  ]

  const activity = [
    { id: '1', when: '2 min ago', who: 'alice@example.com', what: 'signed up' },
    { id: '2', when: '14 min ago', who: 'bob@example.com', what: 'upgraded plan' },
  ]

  return (
    <section aria-labelledby="dashboard-heading">
      <h1 id="dashboard-heading">Overview</h1>

      <div className="dashboard-stats" role="list">
        {stats.map((s) => (
          <Card key={s.label} role="listitem">
            <CardTitle>{s.label}</CardTitle>
            <CardContent><strong>{s.value}</strong></CardContent>
          </Card>
        ))}
      </div>

      <Card>
        <CardTitle>Recent activity</CardTitle>
        <CardContent>
          <TBL
            caption="Recent activity"
            data={activity}
            columns={[
              { header: 'When', accessor: 'when' },
              { header: 'Who', accessor: 'who' },
              { header: 'What', accessor: 'what' },
            ]}
          />
        </CardContent>
      </Card>
    </section>
  )
}
