// Generated by acss-app-builder /app-page error-404
// {{IMPORT_SOURCE:Link}}

export default function {{NAME}}() {
  return (
    <section aria-labelledby="e404-heading" role="alert" className="error-page">
      <h1 id="e404-heading">404 — Page not found</h1>
      <p>We couldn't find the page you were looking for.</p>
      <Link href="/">Return home</Link>
    </section>
  )
}
