// Generated by acss-app-builder /app-page error-500
// {{IMPORT_SOURCE:Button,Link}}

export default function {{NAME}}() {
  return (
    <section aria-labelledby="e500-heading" role="alert" className="error-page">
      <h1 id="e500-heading">500 — Something went wrong</h1>
      <p>An unexpected error occurred. Please try again in a moment.</p>
      <Button type="button" onClick={() => window.location.reload()}>
        Reload
      </Button>{' '}
      <Link href="/">Return home</Link>
    </section>
  )
}
