// Generated by acss-app-builder /app-pattern data-table
// {{IMPORT_SOURCE:TBL,Button}}
import { useMemo, useState } from 'react'

export type DataTableProps<T extends Record<string, unknown>> = {
  caption: string
  data: T[]
  columns: Array<{ header: string; accessor: keyof T; sortable?: boolean }>
  onAction?: (row: T) => void
  actionLabel?: string
}

export default function DataTable<T extends Record<string, unknown>>({
  caption, data, columns, onAction, actionLabel = 'View',
}: DataTableProps<T>) {
  const [sortKey, setSortKey] = useState<keyof T | null>(null)
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('asc')

  const sorted = useMemo(() => {
    if (!sortKey) return data
    const copy = [...data]
    copy.sort((a, b) => {
      const av = a[sortKey]
      const bv = b[sortKey]
      if (av === bv) return 0
      return (av < bv ? -1 : 1) * (sortDir === 'asc' ? 1 : -1)
    })
    return copy
  }, [data, sortKey, sortDir])

  function toggleSort(key: keyof T) {
    if (sortKey === key) {
      setSortDir(sortDir === 'asc' ? 'desc' : 'asc')
    } else {
      setSortKey(key)
      setSortDir('asc')
    }
  }

  const enrichedColumns = [
    ...columns.map((c) => ({
      ...c,
      header: c.sortable ? (
        <button
          type="button"
          onClick={() => toggleSort(c.accessor)}
          aria-sort={sortKey === c.accessor ? (sortDir === 'asc' ? 'ascending' : 'descending') : 'none'}
        >
          {c.header}
        </button>
      ) : c.header,
    })),
    ...(onAction
      ? [{
          header: 'Actions',
          accessor: '__actions' as keyof T,
          cell: (row: T) => (
            <Button type="button" onClick={() => onAction(row)}>
              {actionLabel}
            </Button>
          ),
        }]
      : []),
  ]

  return <TBL caption={caption} data={sorted} columns={enrichedColumns} />
}
