// Generated by acss-app-builder /app-pattern empty-state
// {{IMPORT_SOURCE:Button}}
import type { ReactNode } from 'react'
import './empty-state.scss'

export type EmptyStateProps = {
  title: string
  description?: ReactNode
  actionLabel?: string
  onAction?: () => void
}

export default function EmptyState({ title, description, actionLabel, onAction }: EmptyStateProps) {
  return (
    <div className="empty-state" role="status">
      <h2 className="empty-state__title">{title}</h2>
      {description && <p className="empty-state__description">{description}</p>}
      {actionLabel && onAction && (
        <Button type="button" onClick={onAction} data-color="primary">
          {actionLabel}
        </Button>
      )}
    </div>
  )
}
