// Generated by acss-app-builder /app-pattern hero
// {{IMPORT_SOURCE:Button,Link}}
import type { ReactNode } from 'react'
import './hero.scss'

export type HeroProps = {
  headline: string
  subhead?: ReactNode
  primaryAction?: { label: string; onClick?: () => void; href?: string }
  secondaryAction?: { label: string; href: string }
  /** If true, the hero is the page's primary hero and renders an <h1>. Default: true. */
  isPrimary?: boolean
}

export default function Hero({
  headline, subhead, primaryAction, secondaryAction, isPrimary = true,
}: HeroProps) {
  const Heading = isPrimary ? 'h1' : 'h2'
  return (
    <section className="hero" aria-labelledby="hero-heading">
      <Heading id="hero-heading" className="hero__headline">{headline}</Heading>
      {subhead && <p className="hero__subhead">{subhead}</p>}
      <div className="hero__actions">
        {primaryAction && (
          primaryAction.href
            ? <Link href={primaryAction.href}>{primaryAction.label}</Link>
            : (
              <Button type="button" onClick={primaryAction.onClick} data-color="primary">
                {primaryAction.label}
              </Button>
            )
        )}
        {secondaryAction && <Link href={secondaryAction.href}>{secondaryAction.label}</Link>}
      </div>
    </section>
  )
}
