// Generated by acss-app-builder /app-pattern notification-toast
// {{IMPORT_SOURCE:Button}}
import { useEffect } from 'react'
import './notification-toast.scss'

export type ToastTone = 'info' | 'success' | 'warning' | 'error'

export type NotificationToastProps = {
  message: string
  tone?: ToastTone
  /** ms; set to 0 to disable auto-dismiss. */
  autoDismiss?: number
  onDismiss: () => void
}

export default function NotificationToast({
  message, tone = 'info', autoDismiss = 5000, onDismiss,
}: NotificationToastProps) {
  useEffect(() => {
    if (!autoDismiss) return
    const t = window.setTimeout(onDismiss, autoDismiss)
    return () => window.clearTimeout(t)
  }, [autoDismiss, onDismiss])

  return (
    <div
      className="notification-toast"
      data-tone={tone}
      role={tone === 'error' ? 'alert' : 'status'}
      aria-live={tone === 'error' ? 'assertive' : 'polite'}
    >
      <p className="notification-toast__message">{message}</p>
      <Button
        type="button"
        onClick={onDismiss}
        aria-label="Dismiss notification"
      >
        ×
      </Button>
    </div>
  )
}
